### ISSUE TITLE
Rulerfromtoken won't turn off...

### ISSUE THREAD

**Issue by Wakarusa67** [Nordiii/rulerfromtoken#4]
Rulerfromtoken won't stop measuring. Once the ctrl key is selected the ruler always measures from a selected token.

**Comment by Nordiii** [comment]
Hello could you clarifiy this? I addapted the standard ruler behavior, as soon as you have a ruler it only dissapears when you release the ctrl key and right/left click somewhere.

**Comment by Wakarusa67** [comment]
I can initiate the ruler behavior by pressing ctrl. When I release the ctrl key and click somewhere else it disappears but when I select a target, any target the ruler behavior initiates and follows cursor about with the green ruler. The ctrl key is not pressed during this ongoing behavior and it doesn't seem to toggle on or off with the ctrl key.

**Comment by Nordiii** [comment]
Well, I cannot reproduce it, but I do get an error which should not happen... This could be tied to your problem though. 

I tried to replicate the behavior by doing this:

1. Login as a Player
2. Initiate the ruler once, release ctrl and left click somewhere
3. Target another token by double right clicking on it

**Comment by Valdacil** [comment]
I can confirm the behavior that Wakarusa67 described.  Steps to reproduce:

1. Refresh the browser so that it is a fresh instance.
2. Load a Scene with some tokens on it
3. Drag a token from point A to point B (works normally)
4. Ctrl+Drag token starts ruler
5. Press Space to move along ruler track; upon arrival at destination rule still tied to cursor (problem 1)
6. Click anywhere on the map (ie. deselect); ruler goes away
7. Drag any token; ruler shows drag distance; drop token it moves immediately but ruler is stuck on the cursor
8. At this point the only way I've been able to reset it is to reload the web page

I looked through all of my active modules and didn't see anything that might be conflicting with the ruler behavior.  I did try disabling Deselection but that didn't change anything.  I like the ability to increase/decrease difficult terrain with this, but unfortunately I cannot use it in this state.  I hope you are able to figure out how to reproduce and narrow down this issue.

**Comment by Wakarusa67** [comment]
This seems to be the error messages that I found in the console.

foundry.js:3948 TypeError: An error occurred while rendering TokenHUD 62: Cannot read property 'data' of null
    at TokenHUD.setPosition (foundry.js:23388)
    at TokenHUD._render (foundry.js:4007)
    at async TokenHUD._render (foundry.js:21905)
(anonymous) @ foundry.js:3948
turnmarker.js:56 Uncaught (in promise) TypeError: Cannot read property 'token' of undefined
    at turnmarker.js:56
    at Function._call (foundry.js:2239)
    at Function.call [as __furnace_original_call] (foundry.js:2224)
    at Function.callOriginalFunction (Patches.js:57)
    at Function.<anonymous> (Debug.js:42)
    at foundry.js:10265
    at Array.reduce (<anonymous>)
    at Scene.updateEmbeddedEntity (foundry.js:10253)
    at Token.update (foundry.js:12053)
    at Ruler.moveToken (foundry.js:43281)

**Comment by Nordiii** [comment]
@Valdacil I can only reproduce this behavior:

![Step 1-5](https://user-images.githubusercontent.com/2118629/92980266-be67ce80-f495-11ea-8f6e-9ff60946eab3.gif)

@Wakarusa67 This is an error of a module probably called turn marker or something like that.

Can someone reproduce this on a world with just this module?
If not please send me the **last** line **with the "key"** "core.moduleConfiguration" of the settings.db which can be found under foundrydata(or hower every you named it)/Data/worlds/<your world>/data/settings.db
On linux you can just do "cat settings.db" 
The line should look like this: 
`{"_id":"TwUxrfogGndbZtaH","key":"core.moduleConfiguration","value":"{\"ShowDragDistance\":true,\"rulerfromtoken\":true}"}`

**Comment by Wakarusa67** [comment]
I will try to do a screen capture or turn all modules off and see what happens.

**Comment by Valdacil** [comment]
I tried it again after disaabling Turn Marker.  The behavior persisted.

**Comment by Nordiii** [comment]
@Valdacil it too testet turn marker and it did work, can you reproduce it on a new empty world with just this module?
If you can't then a full list of modules would be helpfull so i can test it myself.

**Comment by Nordiii** [comment]
@Valdacil @Wakarusa67 
I updated again (0.1.2), does this fix the issue for both of you? If not and you cannot reproduce it on an empty world with just this module I would need a module list from both of you.

**Comment by Wakarusa67** [comment]
That seems to have fixed the issue. I can't replicate the behavior. Thanks for your assistance!
